name 'yaml'
maintainer 'Matt Ray'
maintainer_email 'chef@mattray.dev'
license 'Apache-2.0'
description 'Provides YAML Custom Resource'
version '0.2.0'
chef_version '>= 16.0'

issues_url 'https://github.com/mattray/yaml-cookbook/issues'
source_url 'https://github.com/mattray/yaml-cookbook'
